version: '2'
services:

    #####################
    # NGINX
    #####################
    nginx:
        container_name: LEMP_nginx
        image         : nginx:stable
        links         :
            - php
        volumes       :
            - ./html:/var/www/html/
            - ./config/nginx/:/etc/nginx/:ro
        ports:
            - 80:80
            - 443:443

    #####################
    # PHP
    #####################
    php:
        container_name: LEMP_php
        image         : php:7-fpm
        volumes       :
            - ./html:/var/www/html
        depends_on    :
            - db
        links:
            - db
        environment:
            - DB_HOST=lemp
            - DB_NAME=dbuser
            - DB_PASSWORD=dbpass
            - TABLE_PREFIX=lemp_

    #####################
    # DATABASE
    #####################
    db:
        container_name: LEMP_mariadb
        image         : mariadb:latest
        volumes       :
            - ./database:/var/lib/mysql
        environment:
            - MYSQL_ROOT_PASSWORD=root
